user nginx;

worker_processes auto;

server {
    listen 80;

    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }
}

pcre_jit on;

error_log /var/log/nginx/error.log warn;

include /etc/nginx/modules/*.conf;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    server_tokens off;

    client_max_body_size 1m;

    sendfile on;
    sendfile_max_chunk 1m;
    tcp_nopush on;

    access_log /var/log/nginx/access.log main;

    include /etc/nginx/http.d/*.conf;
}
