services: 
  nginx:
    container_name : nginx
    build:
      context: ./requirements/nginx  
      dockerfile: Dockerfile
    ports: 
      - "443:443"
    volumes:
      - ./requirements/web:/var/www/html
    networks:
      - inception
    restart: on-failure
    depends_on:
      - wordpress
  wordpress:
    container_name : wordpress
    build:
      context: ./requirements/wordpress/
      dockerfile: Dockerfile
    ports: 
      - "9000:9000"
    volumes:
      - ./requirements/web:/var/www/html
    environment:
      WP_DB_HOST: mariadb:3306
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_ADMIN_PASSWORD_FILE: /run/secrets/db_admin_password
      MYSQL_EDITOR_PASSWORD_FILE: /run/secrets/db_editor_password
      REDIS_HOST: redis
    secrets:
      - db_admin_password
      - db_editor_password
      - db_password
    networks:
      - inception
    env_file:
      - .env
    restart: on-failure
    depends_on:
      - mariadb
      - redis
      - postfix
  postfix:
    container_name: postfix
    build:
      context: ./requirements/bonus/postfix/
      dockerfile: Dockerfile
    ports:
      - "25:25"
    environment:
      POSTPASS: /run/secrets/post_password
    secrets:
      - post_password
    networks:
      - inception
    env_file:
      - .env
    restart: on-failure
  redis:
    container_name : redis
    build:
      context: ./requirements/bonus/redis/
      dockerfile: Dockerfile
    ports:
      - "6379:6379"
    networks:
      - inception
    restart: always
  mariadb:
    container_name : mariadebezinha
    build:
      context: ./requirements/mariadb/
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
      - db_root_password
    networks:
      - inception
    env_file:
      - .env
    restart: always
secrets:
  post_password:
    file: ./secrets/post_password.txt
  db_editor_password:
    file: ./secrets/db_editor_password.txt
  db_admin_password:
    file: ./secrets/db_admin_password.txt
  db_password:
    file: ./secrets/db_password.txt
  db_root_password:
    file: ./secrets/db_root_password.txt

networks:
  inception:
    driver: bridge