# My Make file





build :
	docker compose up --build
bashdb :
	docker container exec -it mariadebezinha bash
bashnginx:
	docker container exec -it srcs-nginx-1 bash
stopdb:
	docker container stop mariadebezinha
rmdb:
	docker container rm -f mariadebezinha